services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.Backend
    container_name: c-v-q-i-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/best.pt:/src/backend/best.pt
      - ./static:/src/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s    
    restart: always
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: c-v-q-i-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:8000/api/v1/predict
    depends_on:
      backend:
        condition: service_healthy
    restart: always

